### ISSUE TITLE
Algolia error import dependency - Tutorial

### ISSUE THREAD

**Issue by reivaxcorp** [algolia/instantsearch-android-insights#12]
I can't import algolia instantsearch for android:

```
compile 'com.algolia:instantsearch-android:1.+'
// This will automatically update to the latest v1 release when you build.
```
I have the error Gradle project sync failed.

This is the tutorial: https://community.algolia.com/instantsearch-android/getting-started.html

**Comment by PLNech** [comment]
Hi @reivaxcorp, thanks for reporting this!

- Could you share the actual error message you have when Gradle sync fails?
- Does it disappear when you use a fixed version like `implementation 'com.algolia:instantsearch-android:1.13.0'`?

**Comment by PLNech** [comment]
@reivaxcorp, do you still encounter this issue? Reproducing your setup (new application, adding `compile 'com.algolia:instantsearch-android:1.+'`), I don't get any Gradle sync error. 

**If you still encounter the issue, just reopen this ticket and answer the two questions I asked previously :slightly_smiling_face:**
