### ISSUE TITLE
Crash WorkManager

### ISSUE THREAD

**Issue by asalliou** [algolia/instantsearch-android-insights#7]
Hi,

I've been using insight 1.0.2 in my App and 4% of my users experienced some crashes while the app was running in the background.
I turned out to be caused by android.arch.work:work-runtime-ktx:1.0.0-alpha02
This issue is known and solved in work-runtime-ktx:1.0.0-alpha05, is it possible to update this dependency? (https://developer.android.com/jetpack/docs/release-notes#july_24_2018)

Antoine

**Comment by q-litzler** [comment]
Hello Asalliou,

Thank you for your feedback.

You can now use the updated `com.algolia.instantsearch-android:insights:1.0.6` dependency, which includes `work-runtime-ktx:1.0.0-alpha05`.

Let us know if you encounter any issues.

**Comment by asalliou** [comment]
Hello @q-litzler 

Thank's for your feedback. I will restore "insight" in my app as soon as a stable version of this dependency is released and included. I'll watch for a new version.
